// Generated by CoffeeScript 1.8.0
(function() {
  var DEBUG_STATE, DEFAULT_FORMAT, Net_action, request;

  request = require('request');

  DEFAULT_FORMAT = 'json';

  DEBUG_STATE = true;

  module.exports = Net_action = (function() {
    function Net_action(ROOT_DATA) {
      this.ROOT_DATA = ROOT_DATA;
    }

    Net_action.prototype.get = function(_arg) {
      var errorCallback, params, ressource, successCallback;
      ressource = _arg.ressource, params = _arg.params, this.format = _arg.format, successCallback = _arg.successCallback, errorCallback = _arg.errorCallback;
      if (this.format == null) {
        this.format = DEFAULT_FORMAT;
      }
      return this._interact({
        method: 'GET',
        params: params,
        ressource: ressource,
        scb: successCallback,
        ecb: errorCallback
      });
    };

    Net_action.prototype.post = function(_arg) {
      var errorCallback, params, ressource, successCallback;
      ressource = _arg.ressource, params = _arg.params, this.format = _arg.format, successCallback = _arg.successCallback, errorCallback = _arg.errorCallback;
      if (this.format == null) {
        this.format = DEFAULT_FORMAT;
      }
      return this._interact({
        method: 'POST',
        params: params,
        ressource: ressource,
        scb: successCallback,
        ecb: errorCallback
      });
    };

    Net_action.prototype.put = function(_arg) {
      var errorCallback, params, ressource, successCallback;
      ressource = _arg.ressource, params = _arg.params, this.format = _arg.format, successCallback = _arg.successCallback, errorCallback = _arg.errorCallback;
      if (this.format == null) {
        this.format = DEFAULT_FORMAT;
      }
      return this._interact({
        method: 'PUT',
        params: params,
        ressource: ressource,
        scb: successCallback,
        ecb: errorCallback
      });
    };

    Net_action.prototype["delete"] = function(_arg) {
      var errorCallback, ressource, successCallback;
      ressource = _arg.ressource, this.format = _arg.format, successCallback = _arg.successCallback, errorCallback = _arg.errorCallback;
      if (this.format == null) {
        this.format = DEFAULT_FORMAT;
      }
      return this._interact({
        method: 'DELETE',
        ressource: ressource,
        params: null,
        scb: successCallback,
        ecb: errorCallback
      });
    };

    Net_action.prototype._interact = function(_arg) {
      var ecb, method, params, ressource, scb, url;
      method = _arg.method, ressource = _arg.ressource, params = _arg.params, scb = _arg.scb, ecb = _arg.ecb;
      if (this.ROOT_DATA == null) {
        if (DEBUG_STATE) {
          console.error('#[!] No host defined !!');
        }
        return false;
      }
      if (params == null) {
        params = {};
      }
      if (method === "GET") {
        ressource = escape(ressource);
        url = "" + ressource + "?format=" + this.format;
        if ((params != null) && typeof params === 'string') {
          url += "" + params;
          params = '';
        }
      } else {
        url = "" + ressource;
      }
      if (DEBUG_STATE) {
        console.log("#[+] EXEC " + method + " -> " + this.ROOT_DATA + "/" + url);
      }
      return request({
        method: method,
        json: true,
        form: params,
        uri: "" + this.ROOT_DATA + "/" + url
      }, (function(_this) {
        return function(error, response, result) {
          if (result != null) {
            if ((result.State != null) && result.State) {
              return scb(result);
            } else {
              return ecb(result);
            }
          } else {
            return ecb("" + error + "/" + response);
          }
        };
      })(this));
    };

    return Net_action;

  })();

}).call(this);
